config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'pages#home'
  resources :users do
    resources :preferences, only: [:new, :create] do
      resources :coffees, only: [:index, :show]
    end
  end
  resources :coffees, only: [:index, :show, :new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/coffee.rb
# app/models/coffee.rb
class Coffee < ApplicationRecord
  # Associations
  has_many :preferences, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # Validations
  validates :name, presence: true
  validates :origin, presence: true
  validates :roaster, presence: true
  validates :strength, presence: true
  validates :coffee_type, presence: true
  validates :machine_type, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :coffee
end

app/models/preference.rb
# app/models/preference.rb
class Preference < ApplicationRecord
  # Associations
  belongs_to :user
  belongs_to :coffee

  # Validations
  validates :habit, presence: true
  validates :machine_type, presence: true
  validates :coffee_type, presence: true

  
end

app/models/review.rb
# app/models/review.rb
class Review < ApplicationRecord
  # Associations
  belongs_to :coffee

  # Validations
  validates :description, presence: true
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5 }
end

app/models/user.rb
# app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Niveaux disponibles
  LEVELS = ['Débutant', 'Intermédiaire', 'Avancé'].freeze

  # Associations
  has_many :preferences, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reviews, through: :preferences
  has_many :favorite_coffees, through: :favorites, source: :coffee

  # Enum pour le niveau
  enum level: {
    debutant: 'Débutant',
    intermediaire: 'Intermédiaire',
    avance: 'Avancé'
  }

  # Validations
  validates :level, presence: true, inclusion: { in: levels.keys }

  # Méthode pour vérifier le niveau
  def level?(check_level)
    self.level == check_level.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coffees_controller.rb
class CoffeesController < ApplicationController
  before_action :set_coffee, only: [:show]

  def index
    @coffees = Coffee.all
  end

  def show
  end

  def new
    @coffee = Coffee.new
  end

  def create
    @coffee = Coffee.new(coffee_params)
    if @coffee.save
      redirect_to @coffee, notice: 'Coffee was successfully created.'
    else
      render :new
    end
  end

  private

  def set_coffee
    @coffee = Coffee.find(params[:id])
  end

  def coffee_params
    params.require(:coffee).permit(:name, :description, :origin, :roaster, :strength, :coffee_type, :machine_type)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    # Ton code pour la page d'accueil va ici
  end
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :authenticate_user!

  def create
    @preference = Preference.new(preference_params)
    @preference.user_id = current_user.id

    if @preference.save
     
      @coffees = Coffee.where(coffee_form: @preference.coffee_form, coffee_type: @preference.coffee_type)
                       .where("weekly_consumption <= ?", @preference.weekly_consumption.to_i)

      render 'coffees/index'
    else
      render :new
    end
  end

  private

  def preference_params
    params.require(:preference).permit(:coffee_form, :weekly_consumption, :coffee_type)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coffees_helper.rb
module CoffeesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/coffees/create.html.erb
<h1>Coffees#create</h1>
<p>Find me in app/views/coffees/create.html.erb</p>

app/views/coffees/index.html.erb
<!-- app/views/preferences/index.html.erb -->

<h1>Cafés adaptés à vos préférences</h1>

<% if @coffees.present? %>
  <ul>
    <% @coffees.each do |coffee| %>
      <li><%= coffee.name %> - <%= coffee.description %></li>
    <% end %>
  </ul>
<% else %>
  <p>Aucun café correspondant à vos préférences n'a été trouvé.</p>
<% end %>

app/views/coffees/new.html.erb
<div class="container d-flex justify-content-center align-items-center min-vh-100">
  <div class="col-md-8 col-lg-6">
    <h1 class="text-center my-4">New Coffee</h1>

    <%= form_with(model: @coffee, local: true, html: { class: "form-coffee" }) do |form| %>
      <% if @coffee.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(@coffee.errors.count, "error") %> prohibited this coffee from being saved:</h2>

          <ul>
            <% @coffee.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :description, class: "form-label" %>
        <%= form.text_area :description, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :origin, class: "form-label" %>
        <%= form.text_field :origin, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :roaster, class: "form-label" %>
        <%= form.text_field :roaster, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :strength, class: "form-label" %>
        <%= form.number_field :strength, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :coffee_type, class: "form-label" %>
        <%= form.text_field :coffee_type, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :machine_type, class: "form-label" %>
        <%= form.text_field :machine_type, class: "form-control" %>
      </div>

      <div class="d-grid gap-2">
        <%= form.submit "Save Coffee", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>

    <%= link_to 'Back', coffees_path, class: "btn btn-secondary mt-3" %>
  </div>
</div>

app/views/coffees/show.html.erb
<h1><%= @coffee.name %></h1>

<p>
  <strong>Description:</strong>
  <%= @coffee.description %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @coffee.origin %>
</p>

<p>
  <strong>Roaster:</strong>
  <%= @coffee.roaster %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @coffee.strength %>
</p>

<p>
  <strong>Coffee Type:</strong>
  <%= @coffee.coffee_type %>
</p>

<p>
  <strong>Machine Type:</strong>
  <%= @coffee.machine_type %>
</p>

<%= link_to 'Back', coffees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyTools</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap" rel="stylesheet">
  
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>

  <!-- Intégration de Bootstrap CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  
  <!-- Styles personnalisés -->
  <style>
    /* Ajoutez vos styles personnalisés ici */
  </style>
</head>

<body>
  <%= render 'shared/navbar' %> <!-- Inclusion de la vue partielle de la nav bar -->
  <%= yield %>
 

  <!-- Intégration de Bootstrap JS et des dépendances JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

  <!-- Script pour l'effet de navigation sur la barre de navigation -->
  <script>
    var prevScrollpos = window.pageYOffset;
    window.onscroll = function() {
      var currentScrollPos = window.pageYOffset;
      if (prevScrollpos > currentScrollPos) {
        document.getElementById("navbar").style.top = "0";
      } else {
        document.getElementById("navbar").style.top = "-100%";
      }
      prevScrollpos = currentScrollPos;
    }
  </script>
</body>
</html>

app/views/pages/home.html.erb
<h1 class="text-center mt-5">Bienvenue sur notre application de sélection de cafés!</h1>

<% if user_signed_in? %>
  <div class="container mt-4">
    <p class="lead">Bienvenue <%= current_user.email %>!</p>

    <div class="card">
      <div class="card-body">
        <h2 class="card-title">Choisissez vos préférences de café</h2>

        <%= form_with(model: @preference, url: user_preferences_path(current_user), local: true, class: "mt-3") do |form| %>
  <div class="form-group">
    <%= form.label :coffee_form, "Forme de café" %><br>
    <%= form.select :coffee_form, ['Capsule', 'Grain'], { prompt: "Choisissez une option" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :weekly_consumption, "Nombre de cafés par semaine" %><br>
    <%= form.select :weekly_consumption, ['2', '4', 'Plus de 6'], { prompt: "Choisissez une option" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :coffee_type, "Type de café" %><br>
    <%= form.select :coffee_type, ['Arabica', 'Robusta'], { prompt: "Choisissez une option" }, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Enregistrer", class: "btn btn-primary" %>
  </div>
<% end %>

      </div>
    </div>
    </div>

<% else %>
  <div class="container mt-4">
    <p class="lead">Vous n'êtes pas connecté.</p>
    <%= link_to 'S\'inscrire', new_user_registration_path, class: "btn btn-success mr-2" %>
    <%= link_to 'Se connecter', new_user_session_path, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/preferences/create.html.erb
<h1>Preferences#create</h1>
<p>Find me in app/views/preferences/create.html.erb</p>

app/views/preferences/new.html.erb
<!-- app/views/preferences/new.html.erb -->
<h1>Choisissez vos préférences de café</h1>

<%= form_with(model: @preference, url: user_preferences_path(current_user), local: true) do |form| %>
  <div>
    <%= form.label :coffee_form, "Forme de café" %><br>
    <%= form.select :coffee_form, ['Capsule', 'Grain'] %>
  </div>

  <div>
    <%= form.label :weekly_consumption, "Nombre de cafés par semaine" %><br>
    <%= form.select :weekly_consumption, ['2', '4', 'Plus de 6'] %>
  </div>

  <div>
    <%= form.label :coffee_type, "Type de café" %><br>
    <%= form.select :coffee_type, ['Arabica', 'Robusta'] %>
  </div>

  <div>
    <%= form.submit "Enregistrer" %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light">
  <div class="container">
    <%= link_to root_path, class: "navbar-brand" do %>
      BaristApp
    <% end %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Mes préférences', user_preferences_path(current_user), class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'nav-link', data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Se connecter', new_user_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>